### PR TITLE
Update travis badge for branch

### PR DESCRIPTION
**Pull request by jspizziri**

### CODE REVIEW

**Comment by jspizziri** [comment]
@JDutil or @romul 

Whats the status of this extension? It doesn't really seem like its getting any love. 18 open PRs, some of which date back to 2013 (e.g. there's a translation PR that should be a gimme), and a number of issues.

Additionally the build hasn't passed in quite a while. 

I'm willing to participate in whipping it into shape; however if the contributors are unresponsive people are going to stop using it.

**Comment by alepore** [comment]
i started some work to finally get a green build...

**Comment by jspizziri** [comment]
:+1: If I can help with anything let me know.

**Comment by JDutil** [comment]
I don't use this extension and don't really like PayPal so hopefully people such as yourself and @alepore who are actually interested in using it will step up to the plate.

**Comment by jspizziri** [comment]
@JDutil 

Haha, I have a similar distaste for PayPal as well. Unfortunately, I don't have the luxury of telling the client what payment methods they should accept, so for now, I have to deal with it. :'(

**Comment by alepore** [comment]
yeah, no one likes paypal, that's for sure.
i use it in almost every present and future project so i'll try to keep it functional, at least.

**Comment by alepore** [comment]
@jspizziri a good help may be to take a look at open issues about important stuff, error etc

**Comment by JDutil** [comment]
@jspizziri I can add you to this repos team as well if you'd like.

**Comment by jspizziri** [comment]
@JDutil, sure. That'll help me work through some of the old issues and PR's a little better.

**Comment by JDutil** [comment]
Done

**Pull request merged**
